In [116]:
import random
import numpy as np

In [117]:
gamma = np.array([1, 1])
B = np.array([10, 10])
lambd = np.array([0.1, 0.1])
N = 10
a = np.array([[B[0]/N for _ in range(N)], [B[1]/N for _ in range(N)]])
b = np.array([B[0]/2, B[1]/2])
number_of_leaders = 1 # C in the paper?
C = 5
leaders_indices = random.sample(range(N), number_of_leaders)
print(leaders_indices)
rho = np.array([C if index in leaders_indices else 1 for index in range(N)])
x_0 = np.array([0.5 for index in range(N)])
pas = 0.01

[0]


In [118]:
for x in range(100):
    W_0 = [
        np.array([index for index in range(N) if a[0][index]==0]),
        np.array([index for index in range(N) if a[1][index]==0])
        ]
    W_1 = [
        np.array([index for index in range(N) if a[0][index]==b[0]]), 
        np.array([index for index in range(N) if a[1][index]==b[1]])
        ]
    W_2 = [
        np.array([index for index in range(N) if not(index in W_0[0] or index in W_1[0])]),
        np.array([index for index in range(N) if not(index in W_0[1] or index in W_1[1])])
    ]

    # compute mu_0

    sqrt_d = [
        np.sqrt(rho*(np.array([1 for _ in range(N)])-x_0+ a[1])), 
        np.sqrt(rho*(x_0+ a[0]))
    ]
    
    numerator = [
        sum([sqrt_d[0][index] for index in W_2[0]]), 
        sum([sqrt_d[1][index] for index in W_2[1]])]
    denominator = [
        B[0]-b[0]*len(W_1[0])+len(W_2[0])+sum([a[1][index] for index in W_2[0]]),
        B[1]-b[1]*len(W_1[1])+len(W_2[1])+sum([a[0][index] for index in W_2[1]])
        ]

    mu_0 = [
        (numerator[0]/denominator[0])**2 - lambd[0],
        (numerator[1]/denominator[1])**2 - lambd[1]
    ]
    # compute alpha

    alpha = [
        np.sqrt(gamma[0]/(mu_0[0]+lambd[0]))*sqrt_d[0] - 1 - a[1],
        np.sqrt(gamma[1]/(mu_0[1]+lambd[1]))*sqrt_d[1] - 1 - a[0]
    ]

    beta = [
        np.minimum([b[0] for index in range(N)], np.maximum([0 for index in range(N)], alpha[0])),
        np.minimum([b[1] for index in range(N)], np.maximum([0 for index in range(N)], alpha[1]))
    ]
    a = [(beta[0] - a[0])*pas+a[0], (beta[1] - a[1])*pas+a[1]]

print(a[0], a[1], sep='\n')

[3.27297031 0.74744774 0.74744774 0.74744774 0.74744774 0.74744774
 0.74744774 0.74744774 0.74744774 0.74744774]
[3.27297031 0.74744774 0.74744774 0.74744774 0.74744774 0.74744774
 0.74744774 0.74744774 0.74744774 0.74744774]


[array([0.99669973, 0.99669973, 0.99669973, 0.99669973, 1.02970241,
       0.99669973, 0.99669973, 0.99669973, 0.99669973, 0.99669973]), array([1.00669973, 1.00669973, 1.00669973, 1.00669973, 1.03970241,
       1.00669973, 1.00669973, 1.00669973, 1.00669973, 1.00669973])]


[[0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 ...
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]]


[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
